version: "3"
services:
    app:
        image: node:12-alpine
        command: sh -c "yarn install && yarn run dev"
        ports:
            - 7001:7001
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DB: test
    mysql:
        image: mysql:8.0
        container_name: mysql-docker
        command:
            # MySQL8的密码验证方式默认是 caching_sha2_password，但是很多的连接工具还不支持该方式
            # 就需要手动设置下mysql的密码认证方式为以前的 mysql_native_password 方式
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DB: test
        restart: always
        ports:
            - 3306:3306
        # volumes:
        #     - ~/docker/mysql/data:/var/lib/mysql
        #     - ~/docker/mysql/conf:/etc/mysql/conf.d
        #     - ~/docker/mysql/logs:/logs
    jenkins:
        image: "jenkins/jenkins:lts"
        container_name: jenkins
        restart: always
        ports:
            - "8080:8080"
            - "50000:50000"
        # volumes:
        #     - "/data/docker/jenkins:/var/jenkins_home"
